# Generated by Django 4.2 on 2024-08-13 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_remove_word_dont_know_remove_word_known_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="word",
            old_name="definition",
            new_name="batch_definition",
        ),
    ]
