# Generated by Django 4.2 on 2024-08-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_batch_definition_word_batch_definitions"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="dictionaryapi_antonyms",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="dictionaryapi_definitions",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="dictionaryapi_phonetics",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="dictionaryapi_synonyms",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="mymemory_translated_fas",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
