# Generated by Django 4.2 on 2024-08-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0009_word_dictionaryapi_antonyms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="dictionaryapi_json",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="word",
            name="dictionaryapi_yaml",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
