# Generated by Django 4.2 on 2024-08-17 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0010_word_dictionaryapi_json_word_dictionaryapi_yaml"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="google_translation",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
